#%RAML 1.0 Trait
responses:
   200:
          body:
            application/json:
              example:
                {"message": "addition is 20"}
   400:
          body:
            application/json:
              example:
                {"message": "bad server"}
